spring.application.name=productivity

# set the connection properties for the MySQL database
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/productivity-prod-database
spring.datasource.username=root
spring.datasource.password=pratham123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
