package io.github.prathamjainone.productivity.users.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import java.util.Objects;

/**
 * Represents a user in the system.
 * This class contains all the necessary fields related to a user, including validation constraints.
 * It is mapped to a database table "users" for persistence.
 */
@Entity
@Table(name = "users")
public class User {

    /**
     * The unique identifier for the user.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /**
     * The username of the user.
     * Cannot be empty, and must be between 3 and 20 characters.
     */
    @NotBlank(message = "Username is required.")
    @Size(min = 3, max = 20, message = "Username must be between 3 and 20 characters.")
    @Column(nullable = false, unique = true)
    private String username;

    /**
     * The email address of the user.
     * Must be a valid email format.
     */
    @NotBlank(message = "Email is required.")
    @Email(message = "Please provide a valid email address.")
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * The password of the user.
     * Cannot be empty, and must be at least 6 characters.
     */
    @NotBlank(message = "Password is required.")
    @Size(min = 6, message = "Password must be at least 6 characters.")
    @Column(nullable = false)
    private String password;

    /**
     * The full name of the user.
     * Cannot be empty, and must be between 2 and 100 characters.
     */
    @NotBlank(message = "Full name is required.")
    @Size(min = 2, max = 100, message = "Full name must be between 2 and 100 characters.")
    @Column(nullable = false)
    private String fullName;

    /**
     * Default constructor.
     */
    public User() {
    }

    /**
     * Constructor to initialize a user with the given details.
     *
     * @param username the username of the user
     * @param email    the email address of the user
     * @param password the password for the user
     * @param fullName the full name of the user
     */
    public User(String username, String email, String password, String fullName) {
        this.username = username;
        this.email = email;
        this.password = password;
        this.fullName = fullName;
    }

    // Getters and Setters

    /**
     * Gets the unique ID of the user.
     *
     * @return the user's ID
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the unique ID of the user.
     *
     * @param id the user's ID
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Gets the username of the user.
     *
     * @return the user's username
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the username of the user.
     *
     * @param username the user's username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Gets the email address of the user.
     *
     * @return the user's email address
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address of the user.
     *
     * @param email the user's email address
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Gets the password of the user.
     *
     * @return the user's password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the password of the user.
     *
     * @param password the user's password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Gets the full name of the user.
     *
     * @return the user's full name
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the full name of the user.
     *
     * @param fullName the user's full name
     */
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    // Override equals and hashCode for comparison and hashing based on the user details

    /**
     * Compares this user with another object for equality.
     *
     * @param o the object to compare with
     * @return true if the users are equal, otherwise false
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return id == user.id && Objects.equals(username, user.username) && Objects.equals(email, user.email) && Objects.equals(password, user.password) && Objects.equals(fullName, user.fullName);
    }

    /**
     * Returns the hash code for the user based on its details.
     *
     * @return the hash code of the user
     */
    @Override
    public int hashCode() {
        return Objects.hash(id, username, email, password, fullName);
    }

    /**
     * Returns a string representation of the user.
     *
     * @return a string representation of the user with protected password
     */
    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", email='" + email + '\'' +
                ", password='[PROTECTED]'" +
                ", fullName='" + fullName + '\'' +
                '}';
    }
}
